### ISSUE TITLE
where is the api doc?

### ISSUE THREAD

**Issue by ganyao114** [playpauseandstop/Flask-And-Redis#11]

**Comment by playpauseandstop** [comment]
Confirming the bug, for some reason API section is missing in docs. My apologizes. Will try to fix ASAP

**Comment by playpauseandstop** [comment]
Fixed `readthedocs` project settings, API docs now again available at http://flask-and-redis.readthedocs.io/en/latest/#module-flask_redis

Also, just a quick note, as `Flaks-And-Redis` is wrapper around `redis-py` library you able to call any [Redis](http://redis-py.readthedocs.io/en/latest/#contents) method in your Flask app, e.g., 

```py
from flask import Flask
from flask_redis import Redis

app = Flask('testapp')
redis = Redis(app)

redis.set('key', 'value')
assert regis.get('key') == 'value'
```
