### ISSUE TITLE
Installation falled

### ISSUE THREAD

**Issue by KrisLeeCoder** [playpauseandstop/Flask-And-Redis#9]
install failed with "RuntimeError: maximum recursion depth exceeded" in virtualenv, and when I add "sys.setrecursionlimit(1000000)" in setup.py and reinstall it, it returns Segmentation fault: 11. BTW, the env is OS X 10.10.3.

**Comment by playpauseandstop** [comment]
Oops, that's strange. Which Python version you used?

**Comment by KrisLeeCoder** [comment]
Python 2.7.6

**Comment by playpauseandstop** [comment]
Hope this fixed by using Python 2.7.15. 

Have no idea on the source of the bug, maybe it is not related to `Flask-And-Redis` in first place, but the bug with old version of `pip` instead.
